<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dt_diag_klsf_model extends CI_Model
{

    public $table = 'dt_diag_klsf';
    private $table2 = 'dt_pasien';
    public $id = 'id_diag';
    private $id2 = 'id_pasien';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_diag', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('tp_diag', $q);
	$this->db->or_like('kls_antm', $q);
	$this->db->or_like('ket_antm', $q);
	$this->db->or_like('kls_rwyt', $q);
	$this->db->or_like('is_hiv', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select(array('dt_pasien.nm_pasien','dt_diag_klsf.*'));
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_diag', $q);
	$this->db->or_like($this->table.'.id_pasien', $q);
	$this->db->or_like('tp_diag', $q);
	$this->db->or_like('kls_antm', $q);
	$this->db->or_like('ket_antm', $q);
	$this->db->or_like('kls_rwyt', $q);
	$this->db->or_like('is_hiv', $q);
	$this->db->limit($limit, $start);
        $this->db->join($this->table2, $this->table.'.id_pasien = '.$this->table2.'.id_pasien');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    

}

/* End of file Dt_diag_klsf_model.php */
/* Location: ./application/models/Dt_diag_klsf_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-13 10:31:45 */
/* http://harviacode.com */