<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dt_pasien_model extends CI_Model
{

    public $table = 'dt_pasien';
    public $id = 'id_pasien';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pasien', $q);
	$this->db->or_like('nik_pasien', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('jns_klm', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('is_hamil', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('umr_thn', $q);
	$this->db->or_like('umr_bln', $q);
	$this->db->or_like('brt_bdn', $q);
	$this->db->or_like('tg_bdn', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('parut_bcg', $q);
	$this->db->or_like('skor_anak', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pasien', $q);
	$this->db->or_like('nik_pasien', $q);
	$this->db->or_like('nm_pasien', $q);
	$this->db->or_like('jns_klm', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('is_hamil', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('umr_thn', $q);
	$this->db->or_like('umr_bln', $q);
	$this->db->or_like('brt_bdn', $q);
	$this->db->or_like('tg_bdn', $q);
	$this->db->or_like('telp', $q);
	$this->db->or_like('parut_bcg', $q);
	$this->db->or_like('skor_anak', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dt_pasien_model.php */
/* Location: ./application/models/Dt_pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-20 17:45:13 */
/* http://harviacode.com */