<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dt_pemeriksaan_model extends CI_Model
{

    public $table = 'dt_pemeriksaan';
    public $table2 = 'dt_proses';
    public $id = 'id_periksa';
    public $id2 = 'id_proses';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
//        $this->db->like('id_periksa', $q);
	$this->db->or_like('id_proses', $q);
//	$this->db->or_like('tgl_periksa', $q);
//	$this->db->or_like('noreg', $q);
//	$this->db->or_like('jenis', $q);
//	$this->db->or_like('nilai', $q);
//	$this->db->or_like('ket', $q);
//	$this->db->or_like('create_at', $q);
//	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
//        $this->db->like('id_periksa', $q);
	$this->db->or_like($this->table.'.id_proses', $q);
//	$this->db->or_like('tgl_periksa', $q);
//	$this->db->or_like('noreg', $q);
//	$this->db->or_like('jenis', $q);
//	$this->db->or_like('nilai', $q);
//	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        $this->db->join($this->table2, $this->table.'.id_proses = '.$this->table2.'.id_proses');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dt_pemeriksaan_model.php */
/* Location: ./application/models/Dt_pemeriksaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-25 10:33:04 */
/* http://harviacode.com */