<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dt_thpan_model extends CI_Model
{

    public $table = 'dt_thpan';
    public $table2 = 'dt_proses';
    public $table3 = 'dt_obat';
    public $id = 'id_thp';
    public $id2 = 'id_proses';
    public $id3 = 'id_obat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
//        $this->db->like('id_thp', $q);
//	$this->db->or_like('id_obat', $q);
	$this->db->or_like('id_proses', $q);
//	$this->db->or_like('hari', $q);
//	$this->db->or_like('sisa_obat', $q);
//	$this->db->or_like('ket', $q);
//	$this->db->or_like('create_at', $q);
//	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    
    function get_limit_by($id2,$id3){
        $this->db->limit(1, 0);
        $this->db->where($this->id2, $id2);
        $this->db->where($this->id3, $id3);
        return $this->db->get($this->table)->result();
    }
    
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
//        $this->db->like('id_thp', $q);
//	$this->db->or_like($this->table.'.id_obat', $q);
	$this->db->where($this->table.'.id_proses', $q);
//	$this->db->or_like('hari', $q);
//	$this->db->or_like('sisa_obat', $q);
//	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        $this->db->join($this->table2, $this->table.'.id_proses = '.$this->table2.'.id_proses');
        $this->db->join($this->table3, $this->table.'.id_obat = '.$this->table3.'.id_obat');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dt_thpan_model.php */
/* Location: ./application/models/Dt_thpan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-18 06:17:54 */
/* http://harviacode.com */